services:
  db:
    image: postgres:15
    container_name: hypermotion_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password_local
      - POSTGRES_DB=hypermotion_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
